spring.application.name=auth-service

# db (postgres) configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/nexus
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Rate Limiting Configuration
rate.limiter.bucket-capacity=100
rate.limiter.refill-period=1s
rate.limiter.refill-tokens=10